// flow-typed signature: 90fb1839fc17cae02cda124d00c6863e
// flow-typed version: <<STUB>>/@material-ui/core/Button_v3.9.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/Button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/Button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/Button/Button' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/Button/Button.js' {
  declare module.exports: $Exports<'@material-ui/core/Button/Button'>;
}
declare module '@material-ui/core/Button/index' {
  declare module.exports: $Exports<'@material-ui/core/Button'>;
}
declare module '@material-ui/core/Button/index.js' {
  declare module.exports: $Exports<'@material-ui/core/Button'>;
}
