// flow-typed signature: f800ac0a87055ea7cb8feb593a72d581
// flow-typed version: <<STUB>>/@material-ui/core/DialogContentText_v3.9.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/DialogContentText'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/DialogContentText' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/DialogContentText/DialogContentText' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/DialogContentText/DialogContentText.js' {
  declare module.exports: $Exports<'@material-ui/core/DialogContentText/DialogContentText'>;
}
declare module '@material-ui/core/DialogContentText/index' {
  declare module.exports: $Exports<'@material-ui/core/DialogContentText'>;
}
declare module '@material-ui/core/DialogContentText/index.js' {
  declare module.exports: $Exports<'@material-ui/core/DialogContentText'>;
}
