// flow-typed signature: 2d552c2b24f35e80d09bbb5c24056fcd
// flow-typed version: <<STUB>>/@material-ui/core/DialogActions_v3.9.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/DialogActions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/DialogActions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/DialogActions/DialogActions' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/DialogActions/DialogActions.js' {
  declare module.exports: $Exports<'@material-ui/core/DialogActions/DialogActions'>;
}
declare module '@material-ui/core/DialogActions/index' {
  declare module.exports: $Exports<'@material-ui/core/DialogActions'>;
}
declare module '@material-ui/core/DialogActions/index.js' {
  declare module.exports: $Exports<'@material-ui/core/DialogActions'>;
}
