// flow-typed signature: 33dd35c06324addd6745d4d1e97aac32
// flow-typed version: <<STUB>>/@material-ui/core/DialogContent_v3.9.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/DialogContent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/DialogContent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/DialogContent/DialogContent' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/DialogContent/DialogContent.js' {
  declare module.exports: $Exports<'@material-ui/core/DialogContent/DialogContent'>;
}
declare module '@material-ui/core/DialogContent/index' {
  declare module.exports: $Exports<'@material-ui/core/DialogContent'>;
}
declare module '@material-ui/core/DialogContent/index.js' {
  declare module.exports: $Exports<'@material-ui/core/DialogContent'>;
}
