// flow-typed signature: 7f18ab394255428f2b1b6ffbef72b84c
// flow-typed version: <<STUB>>/@material-ui/core/DialogTitle_v3.9.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/DialogTitle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/DialogTitle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/DialogTitle/DialogTitle' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/DialogTitle/DialogTitle.js' {
  declare module.exports: $Exports<'@material-ui/core/DialogTitle/DialogTitle'>;
}
declare module '@material-ui/core/DialogTitle/index' {
  declare module.exports: $Exports<'@material-ui/core/DialogTitle'>;
}
declare module '@material-ui/core/DialogTitle/index.js' {
  declare module.exports: $Exports<'@material-ui/core/DialogTitle'>;
}
