// flow-typed signature: 9d8556bbe7e4d5ed97ff3a95949c5f33
// flow-typed version: <<STUB>>/@material-ui/core/Dialog_v3.9.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/core/Dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/core/Dialog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/core/Dialog/Dialog' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/core/Dialog/Dialog.js' {
  declare module.exports: $Exports<'@material-ui/core/Dialog/Dialog'>;
}
declare module '@material-ui/core/Dialog/index' {
  declare module.exports: $Exports<'@material-ui/core/Dialog'>;
}
declare module '@material-ui/core/Dialog/index.js' {
  declare module.exports: $Exports<'@material-ui/core/Dialog'>;
}
