// flow-typed signature: 4fd1dcd2f7017f7532325d9b5fbad99d
// flow-typed version: <<STUB>>/@material-ui/styles_vlatest/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/styles/createGenerateClassName' {
  declare module.exports: any;
}

declare module '@material-ui/styles/createStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/createGenerateClassName' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/createStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/getStylesCreator' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/getThemeProps' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/hoistInternalStatics' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/indexCounter' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/install' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/jssPreset' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/makeStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/mergeClasses' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/multiKeyStore' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/styled' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/StylesProvider' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/ThemeContext' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/ThemeProvider' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/useTheme' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/withStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/withTheme' {
  declare module.exports: any;
}

declare module '@material-ui/styles/getStylesCreator' {
  declare module.exports: any;
}

declare module '@material-ui/styles/getThemeProps' {
  declare module.exports: any;
}

declare module '@material-ui/styles/hoistInternalStatics' {
  declare module.exports: any;
}

declare module '@material-ui/styles/index.es' {
  declare module.exports: any;
}

declare module '@material-ui/styles/indexCounter' {
  declare module.exports: any;
}

declare module '@material-ui/styles/install' {
  declare module.exports: any;
}

declare module '@material-ui/styles/jssPreset' {
  declare module.exports: any;
}

declare module '@material-ui/styles/makeStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/mergeClasses' {
  declare module.exports: any;
}

declare module '@material-ui/styles/multiKeyStore' {
  declare module.exports: any;
}

declare module '@material-ui/styles/styled' {
  declare module.exports: any;
}

declare module '@material-ui/styles/StylesProvider' {
  declare module.exports: any;
}

declare module '@material-ui/styles/ThemeContext' {
  declare module.exports: any;
}

declare module '@material-ui/styles/ThemeProvider' {
  declare module.exports: any;
}

declare module '@material-ui/styles/useTheme' {
  declare module.exports: any;
}

declare module '@material-ui/styles/withStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/withTheme' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/styles/createGenerateClassName.js' {
  declare module.exports: $Exports<'@material-ui/styles/createGenerateClassName'>;
}
declare module '@material-ui/styles/createStyles.js' {
  declare module.exports: $Exports<'@material-ui/styles/createStyles'>;
}
declare module '@material-ui/styles/es/createGenerateClassName.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/createGenerateClassName'>;
}
declare module '@material-ui/styles/es/createStyles.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/createStyles'>;
}
declare module '@material-ui/styles/es/getStylesCreator.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/getStylesCreator'>;
}
declare module '@material-ui/styles/es/getThemeProps.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/getThemeProps'>;
}
declare module '@material-ui/styles/es/hoistInternalStatics.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/hoistInternalStatics'>;
}
declare module '@material-ui/styles/es/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/index'>;
}
declare module '@material-ui/styles/es/indexCounter.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/indexCounter'>;
}
declare module '@material-ui/styles/es/install.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/install'>;
}
declare module '@material-ui/styles/es/jssPreset.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/jssPreset'>;
}
declare module '@material-ui/styles/es/makeStyles.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/makeStyles'>;
}
declare module '@material-ui/styles/es/mergeClasses.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/mergeClasses'>;
}
declare module '@material-ui/styles/es/multiKeyStore.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/multiKeyStore'>;
}
declare module '@material-ui/styles/es/styled.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/styled'>;
}
declare module '@material-ui/styles/es/StylesProvider.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/StylesProvider'>;
}
declare module '@material-ui/styles/es/ThemeContext.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/ThemeContext'>;
}
declare module '@material-ui/styles/es/ThemeProvider.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/ThemeProvider'>;
}
declare module '@material-ui/styles/es/useTheme.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/useTheme'>;
}
declare module '@material-ui/styles/es/withStyles.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/withStyles'>;
}
declare module '@material-ui/styles/es/withTheme.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/withTheme'>;
}
declare module '@material-ui/styles/getStylesCreator.js' {
  declare module.exports: $Exports<'@material-ui/styles/getStylesCreator'>;
}
declare module '@material-ui/styles/getThemeProps.js' {
  declare module.exports: $Exports<'@material-ui/styles/getThemeProps'>;
}
declare module '@material-ui/styles/hoistInternalStatics.js' {
  declare module.exports: $Exports<'@material-ui/styles/hoistInternalStatics'>;
}
declare module '@material-ui/styles/index.es.js' {
  declare module.exports: $Exports<'@material-ui/styles/index.es'>;
}
declare module '@material-ui/styles/index' {
  declare module.exports: $Exports<'@material-ui/styles'>;
}
declare module '@material-ui/styles/index.js' {
  declare module.exports: $Exports<'@material-ui/styles'>;
}
declare module '@material-ui/styles/indexCounter.js' {
  declare module.exports: $Exports<'@material-ui/styles/indexCounter'>;
}
declare module '@material-ui/styles/install.js' {
  declare module.exports: $Exports<'@material-ui/styles/install'>;
}
declare module '@material-ui/styles/jssPreset.js' {
  declare module.exports: $Exports<'@material-ui/styles/jssPreset'>;
}
declare module '@material-ui/styles/makeStyles.js' {
  declare module.exports: $Exports<'@material-ui/styles/makeStyles'>;
}
declare module '@material-ui/styles/mergeClasses.js' {
  declare module.exports: $Exports<'@material-ui/styles/mergeClasses'>;
}
declare module '@material-ui/styles/multiKeyStore.js' {
  declare module.exports: $Exports<'@material-ui/styles/multiKeyStore'>;
}
declare module '@material-ui/styles/styled.js' {
  declare module.exports: $Exports<'@material-ui/styles/styled'>;
}
declare module '@material-ui/styles/StylesProvider.js' {
  declare module.exports: $Exports<'@material-ui/styles/StylesProvider'>;
}
declare module '@material-ui/styles/ThemeContext.js' {
  declare module.exports: $Exports<'@material-ui/styles/ThemeContext'>;
}
declare module '@material-ui/styles/ThemeProvider.js' {
  declare module.exports: $Exports<'@material-ui/styles/ThemeProvider'>;
}
declare module '@material-ui/styles/useTheme.js' {
  declare module.exports: $Exports<'@material-ui/styles/useTheme'>;
}
declare module '@material-ui/styles/withStyles.js' {
  declare module.exports: $Exports<'@material-ui/styles/withStyles'>;
}
declare module '@material-ui/styles/withTheme.js' {
  declare module.exports: $Exports<'@material-ui/styles/withTheme'>;
}
